version: '3.8'

services:
  api:
    build:
      context: ./python-api
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    depends_on:
      - MySqlDb
    env_file:
      - ./python-api/.env
    networks:
      - app-networks
    command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]  

  MySqlDb:
    image: mysql:5.7
    container_name: MySqlDb
    env_file:
      - ./python-api/.env
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./python-api/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    networks:
      - app-networks

networks:
  app-networks:
    driver: bridge   

volumes:
  mysql-data:
