version: '3.8'

services:
  api:
    build:
      context: ./python-api
    container_name: flask-api
    ports:
      - "5000:5000"
    depends_on:
      - database
    environment:
      - DB_HOST=database
      - DB_USER=root
      - DB_PASSWORD=apiDB@523
      - DB_NAME=taskmap_db

  database:
    image: mysql:5.7
    container_name: mySqlDb
    environment:
      - MYSQL_ROOT_PASSWORD=TDroot@5
      - MYSQL_DATABASE=taskmap_db
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./python-api/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

volumes:
  mysql-data:
